In [1]:
import pyarrow.parquet as pq
import pandas as pd
import os

In [9]:
path = os.path.join('datas', 'ebnerd_demo','train', 'behaviors.parquet')
#print(path)
behaviors = pq.read_table(path).to_pandas()
behaviors.isna().sum()/behaviors.shape[0]
behaviors.dropna(inplace=True)
behaviors

,impression_id,article_id,impression_time,read_time,scroll_percentage,device_type,article_ids_inview,article_ids_clicked,user_id,is_sso_user,gender,postcode,age,is_subscriber,session_id,next_read_time,next_scroll_percentage
283,5068020,9777693.0,2023-05-23 13:44:31,88.0,100.0,2,"[9777804, 9777190, 9777565, 9777319, 9777529]",[9777319],1500590,True,0.0,0.0,60.0,True,12846,19.0,83.0
284,5068022,9777565.0,2023-05-23 13:35:43,106.0,100.0,2,"[9738729, 9777565, 9777529, 9765965, 9777804]",[9738729],1500590,True,0.0,0.0,60.0,True,12846,215.0,100.0
286,5068027,9777529.0,2023-05-23 13:41:05,141.0,100.0,2,"[9777529, 9777565, 9777804, 9777704, 9700074]",[9777804],1500590,True,0.0,0.0,60.0,True,12846,39.0,100.0
3101,68748396,9778328.0,2023-05-23 20:23:08,220.0,100.0,2,"[9220931, 9778310, 9778257, 9777941, 9761586, ...",[9220931],1500590,True,0.0,0.0,60.0,True,12848,207.0,100.0
4436,102365531,9773356.0,2023-05-20 09:42:19,60.0,100.0,2,"[9773376, 9773356, 9772300, 9773295, 9771626, ...",[9769504],1594652,True,0.0,1.0,60.0,True,25640,59.0,100.0
4437,102365534,9773356.0,2023-05-20 09:00:39,29.0,100.0,2,"[9772629, 9772601, 9773297, 9203920, 9773296, ...",[9773297],1594652,True,0.0,1.0,60.0,True,25639,2.0,33.0
5664,133495916,9774764.0,2023-05-21 15:28:11,23.0,100.0,2,"[9770028, 9772957, 9774626, 9774358, 9099237, ...",[9774708],1500590,True,0.0,0.0,60.0,True,12834,13.0,87.0
5666,133495919,9774764.0,2023-05-21 15:26:28,72.0,100.0,2,"[9774358, 9771992, 9774789, 9774899, 9774542, ...",[9774840],1500590,True,0.0,0.0,60.0,True,12834,30.0,100.0
6696,156742078,9771042.0,2023-05-18 08:23:58,39.0,100.0,2,"[9770178, 9770729, 9769306, 9735909, 9727087, ...",[9766140],1500590,True,0.0,0.0,60.0,True,12820,82.0,100.0
6697,156742081,9770729.0,2023-05-18 08:22:57,60.0,100.0,2,"[9770886, 9767697, 9770729, 9771083, 9771042]",[9771042],1500590,True,0.0,0.0,60.0,True,12820,39.0,100.0
7497,178013524,9774376.0,2023-05-21 07:38:44,60.0,100.0,2,"[9768150, 9773985, 9774376, 9767675, 9774392]",[9774392],1594652,True,0.0,1.0,60.0,True,25647,48.0,100.0
13187,317174181,9772284.0,2023-05-19 09:45:30,16.0,100.0,2,"[9772256, 9772284, 9772168, 9772263, 9770051, ...",[9772168],1500590,True,0.0,0.0,60.0,True,12823,58.0,100.0
13966,334071765,9774032.0,2023-05-21 10:35:19,27.0,100.0,2,"[9774430, 9774527, 9774404, 9774568, 9774032, ...",[9773003],1594652,True,0.0,1.0,60.0,True,25649,31.0,80.0
15441,369391822,9776508.0,2023-05-22 21:24:30,26.0,100.0,2,"[9776508, 9776560, 9775804, 9776049, 9776385, ...",[9776385],1500590,True,0.0,0.0,60.0,True,12840,13.0,100.0
15442,369391823,9776508.0,2023-05-22 21:22:48,101.0,100.0,2,"[9776385, 9776560, 9775804, 9776508, 9776449, ...",[9776508],1500590,True,0.0,0.0,60.0,True,12840,26.0,100.0
15443,369391826,9776385.0,2023-05-22 21:24:57,13.0,100.0,2,"[9776449, 9776560, 9776508, 9775763, 9776385, ...",[9776449],1500590,True,0.0,0.0,60.0,True,12840,179.0,100.0
15445,369391830,9776449.0,2023-05-22 21:25:10,179.0,100.0,2,"[7306652, 9776560, 9776148, 9774559, 9775804, ...",[9771995],1500590,True,0.0,0.0,60.0,True,12840,9.0,49.0
15773,375218709,9775076.0,2023-05-21 17:53:04,94.0,100.0,2,"[9774648, 9774789, 9775184, 9775079, 9775183, ...",[9774764],1594652,True,0.0,1.0,60.0,True,25655,29.0,100.0
20265,473611596,9772032.0,2023-05-19 06:51:37,26.0,100.0,2,"[9772082, 9767909, 9772032, 9772088, 9771127, ...",[9772045],1500590,True,0.0,0.0,60.0,True,12822,35.0,100.0
20839,487225967,9774626.0,2023-05-21 13:40:47,39.0,100.0,2,"[9774015, 9774403, 9774618, 9774708, 9774764, ...",[9774706],1500590,True,0.0,0.0,60.0,True,12832,18.0,100.0
20840,487225968,9774708.0,2023-05-21 13:40:17,29.0,100.0,2,"[9774626, 9774764, 9774618, 9774706, 9774708, ...",[9774626],1500590,True,0.0,0.0,60.0,True,12832,39.0,100.0
20871,487610553,9771758.0,2023-05-18 18:01:37,782.0,100.0,2,"[9771113, 9711985, 9370125, 9767470, 9770283, ...",[9771224],1594652,True,0.0,1.0,60.0,True,25616,26.0,100.0

In [25]:
path = os.path.join('datas', 'ebnerd_demo','train', 'history.parquet')
#print(path)
history = pq.read_table(path).to_pandas()
history
#legs.describe()

,user_id,impression_time_fixed,scroll_percentage_fixed,article_id_fixed,read_time_fixed
0,13538,"[2023-04-27T10:17:43.000000, 2023-04-27T10:18:...","[100.0, 35.0, 100.0, 24.0, 100.0, 23.0, 100.0,...","[9738663, 9738569, 9738663, 9738490, 9738663, ...","[17.0, 12.0, 4.0, 5.0, 4.0, 9.0, 5.0, 46.0, 11..."
1,58608,"[2023-04-27T18:48:09.000000, 2023-04-27T18:48:...","[37.0, 61.0, 100.0, 100.0, 55.0, 100.0, 100.0,...","[9739362, 9739179, 9738567, 9739344, 9739202, ...","[2.0, 24.0, 72.0, 65.0, 11.0, 4.0, 101.0, 0.0,..."
2,95507,"[2023-04-27T15:20:28.000000, 2023-04-27T15:20:...","[60.0, 100.0, 100.0, 21.0, 29.0, 67.0, 49.0, 5...","[9739035, 9738646, 9634967, 9738902, 9735495, ...","[18.0, 29.0, 51.0, 12.0, 10.0, 10.0, 13.0, 24...."
3,106588,"[2023-04-27T08:29:09.000000, 2023-04-27T08:29:...","[24.0, 57.0, 100.0, nan, nan, 100.0, 100.0, 73...","[9738292, 9738216, 9737266, 9737556, 9737657, ...","[9.0, 15.0, 42.0, 9.0, 3.0, 58.0, 26.0, 214.0,..."
4,617963,"[2023-04-27T14:42:25.000000, 2023-04-27T14:43:...","[100.0, 100.0, nan, 46.0, 23.0, 19.0, 61.0, 70...","[9739035, 9739088, 9738902, 9738968, 9738760, ...","[45.0, 29.0, 116.0, 26.0, 34.0, 42.0, 58.0, 59..."
...,...,...,...,...,...
1585,1122370,"[2023-05-09T06:50:19.000000, 2023-05-09T06:51:...","[100.0, 100.0, 100.0, 100.0, nan]","[9755181, 9706958, 9709329, 9706958, 9755571]","[84.0, 115.0, 298.0, 5.0, 79.0]"
1586,1718049,"[2023-05-17T05:04:36.000000, 2023-05-17T05:04:...","[53.0, 100.0, 24.0, 100.0, 83.0, 28.0, 37.0, 4...","[9768583, 9728166, 9768829, 9769641, 9769994, ...","[13.0, 17.0, 7.0, 99.0, 5.0, 8.0, 4.0, 2.0, 4.0]"
1587,1178033,"[2023-04-29T19:36:47.000000, 2023-04-29T19:37:...","[nan, 98.0, 92.0, 30.0, 35.0, 9.0, 34.0, 58.0,...","[9742268, 9742423, 9742270, 9742440, 9742459, ...","[10.0, 74.0, 89.0, 10.0, 1.0, 4.0, 11.0, 7.0, ..."
1588,395912,"[2023-05-12T05:12:34.000000, 2023-05-12T05:12:...","[100.0, 100.0, 100.0, 33.0, nan]","[9760741, 9760998, 9760935, 9754442, 9760935]","[16.0, 22.0, 23.0, 9.0, 0.0]"
1589,2539047,"[2023-05-09T10:37:17.000000, 2023-05-09T10:37:...","[46.0, 100.0, 40.0, 100.0, 100.0, 100.0, 28.0,...","[9755964, 9755980, 9754081, 9755980, 9755849, ...","[4.0, 23.0, 12.0, 7.0, 28.0, 5.0, 1.0, 10.0, 7..."

In [36]:
path = os.path.join('datas', 'ebnerd_demo', 'articles.parquet')
#print(path)
articles = pq.read_table(path).to_pandas()
articles.isna().sum()/len(legs)
len(articles.loc[:,'article_id'].unique())
#legs.describe()

11777

In [34]:
len(behaviors.loc[:,'article_id'].unique())

923