In [19]:
import pyarrow.parquet as pq
import pandas as pd
import os

In [24]:
path = os.path.join('datas', 'ebnerd_demo','train', 'behaviors.parquet')
#print(path)
behaviors = pq.read_table(path).to_pandas()
behaviors.describe()

,impression_id,article_id,impression_time,read_time,scroll_percentage,device_type,user_id,gender,postcode,age,session_id,next_read_time,next_scroll_percentage
count,2.472400e+04,7.378000e+03,24724,24724.000000,7242.000000,24724.000000,2.472400e+04,1797.000000,361.000000,617.000000,24724.000000,24051.000000,21967.000000
mean,2.927584e+08,9.767142e+06,2023-05-21 17:23:50.627487,45.315239,99.503036,1.690746,1.248888e+06,0.117974,1.027701,52.269044,104320.226541,68.218948,69.568535
min,4.840100e+04,3.971783e+06,2023-05-18 07:00:03,0.000000,9.000000,1.000000,1.131300e+04,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,1.469011e+08,9.772089e+06,2023-05-19 19:52:59,12.000000,100.000000,1.000000,6.214020e+05,0.000000,0.000000,40.000000,52543.750000,7.000000,37.000000
50%,2.963424e+08,9.774352e+06,2023-05-21 17:39:49.500000,21.000000,100.000000,2.000000,1.246374e+06,0.000000,1.000000,60.000000,105408.000000,21.000000,82.000000
75%,4.365403e+08,9.776870e+06,2023-05-23 11:01:42.500000,45.000000,100.000000,2.000000,1.887792e+06,0.000000,2.000000,60.000000,156941.000000,62.000000,100.000000
max,5.800973e+08,9.780271e+06,2023-05-25 06:59:52,1799.000000,100.000000,3.000000,2.589391e+06,1.000000,4.000000,70.000000,212376.000000,1797.000000,100.000000
std,1.679379e+08,1.140635e+05,NaN,95.248093,5.397873,0.525815,7.411897e+05,0.322668,1.115202,13.605250,60094.285810,167.465073,32.256432

In [25]:
path = os.path.join('datas', 'ebnerd_demo','train', 'history.parquet')
#print(path)
history = pq.read_table(path).to_pandas()
history
#legs.describe()

,user_id,impression_time_fixed,scroll_percentage_fixed,article_id_fixed,read_time_fixed
0,13538,"[2023-04-27T10:17:43.000000, 2023-04-27T10:18:...","[100.0, 35.0, 100.0, 24.0, 100.0, 23.0, 100.0,...","[9738663, 9738569, 9738663, 9738490, 9738663, ...","[17.0, 12.0, 4.0, 5.0, 4.0, 9.0, 5.0, 46.0, 11..."
1,58608,"[2023-04-27T18:48:09.000000, 2023-04-27T18:48:...","[37.0, 61.0, 100.0, 100.0, 55.0, 100.0, 100.0,...","[9739362, 9739179, 9738567, 9739344, 9739202, ...","[2.0, 24.0, 72.0, 65.0, 11.0, 4.0, 101.0, 0.0,..."
2,95507,"[2023-04-27T15:20:28.000000, 2023-04-27T15:20:...","[60.0, 100.0, 100.0, 21.0, 29.0, 67.0, 49.0, 5...","[9739035, 9738646, 9634967, 9738902, 9735495, ...","[18.0, 29.0, 51.0, 12.0, 10.0, 10.0, 13.0, 24...."
3,106588,"[2023-04-27T08:29:09.000000, 2023-04-27T08:29:...","[24.0, 57.0, 100.0, nan, nan, 100.0, 100.0, 73...","[9738292, 9738216, 9737266, 9737556, 9737657, ...","[9.0, 15.0, 42.0, 9.0, 3.0, 58.0, 26.0, 214.0,..."
4,617963,"[2023-04-27T14:42:25.000000, 2023-04-27T14:43:...","[100.0, 100.0, nan, 46.0, 23.0, 19.0, 61.0, 70...","[9739035, 9739088, 9738902, 9738968, 9738760, ...","[45.0, 29.0, 116.0, 26.0, 34.0, 42.0, 58.0, 59..."
...,...,...,...,...,...
1585,1122370,"[2023-05-09T06:50:19.000000, 2023-05-09T06:51:...","[100.0, 100.0, 100.0, 100.0, nan]","[9755181, 9706958, 9709329, 9706958, 9755571]","[84.0, 115.0, 298.0, 5.0, 79.0]"
1586,1718049,"[2023-05-17T05:04:36.000000, 2023-05-17T05:04:...","[53.0, 100.0, 24.0, 100.0, 83.0, 28.0, 37.0, 4...","[9768583, 9728166, 9768829, 9769641, 9769994, ...","[13.0, 17.0, 7.0, 99.0, 5.0, 8.0, 4.0, 2.0, 4.0]"
1587,1178033,"[2023-04-29T19:36:47.000000, 2023-04-29T19:37:...","[nan, 98.0, 92.0, 30.0, 35.0, 9.0, 34.0, 58.0,...","[9742268, 9742423, 9742270, 9742440, 9742459, ...","[10.0, 74.0, 89.0, 10.0, 1.0, 4.0, 11.0, 7.0, ..."
1588,395912,"[2023-05-12T05:12:34.000000, 2023-05-12T05:12:...","[100.0, 100.0, 100.0, 33.0, nan]","[9760741, 9760998, 9760935, 9754442, 9760935]","[16.0, 22.0, 23.0, 9.0, 0.0]"
1589,2539047,"[2023-05-09T10:37:17.000000, 2023-05-09T10:37:...","[46.0, 100.0, 40.0, 100.0, 100.0, 100.0, 28.0,...","[9755964, 9755980, 9754081, 9755980, 9755849, ...","[4.0, 23.0, 12.0, 7.0, 28.0, 5.0, 1.0, 10.0, 7..."

In [36]:
path = os.path.join('datas', 'ebnerd_demo', 'articles.parquet')
#print(path)
articles = pq.read_table(path).to_pandas()
articles.isna().sum()/len(legs)
len(articles.loc[:,'article_id'].unique())
#legs.describe()

11777

In [34]:
len(behaviors.loc[:,'article_id'].unique())

923